personalWebsite/main/routes.py
from flask import render_template, request, Blueprint
from personalWebsite import db, bcrypt
from personalWebsite.models import HomePost


main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = HomePost.query.order_by(HomePost.id.desc()).paginate(page=page, per_page=6)
    return render_template('index.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html')

personalWebsite/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from personalWebsite import db, bcrypt
from personalWebsite.posts.forms import PostForm
from personalWebsite.models import Project, HomePost
from personalWebsite.posts.utils import (save_file, save_project_files, get_project_files,
                                        set_type_image, get_first_files, delete_project_files)

posts = Blueprint('posts', __name__)

@posts.route('/project/<title>')
def project(title):
    project_post = Project.query.filter_by(title=title).first()
    #still assigning files as so and potentially returning None makes this easier on the Jinga templating
    files = get_project_files(project_post)
    return render_template('project.html', project_post=project_post, files=files)

@posts.route('/updates')
def updates():
    page = request.args.get('page', 1, type=int)
    posts = Project.query.filter_by(type='update').order_by(Project.id.desc()).paginate(page=page, per_page=10)
    return render_template('updates.html', posts=posts)

@posts.route('/coding')
def coding():
    page = request.args.get('page', 1, type=int)
    posts = Project.query.filter_by(type='coding').order_by(Project.id.desc()).paginate(page=page, per_page=10)
    return render_template('coding.html', posts=posts)

@posts.route('/writings')
def writings():
    page = request.args.get('page', 1, type=int)
    posts = Project.query.filter_by(type='writing').order_by(Project.id.desc()).paginate(page=page, per_page=10)
    return render_template('writings.html', posts=posts)

@posts.route('/photography')
def photography():
    page = request.args.get('page', 1, type=int)
    posts = Project.query.filter_by(type='photography').order_by(Project.id.desc())
    files = get_first_files(posts)
    posts=posts.paginate(page=page, per_page=10)
    return render_template('photography.html', posts=posts, files=files)



@posts.route('/addpost', methods=['GET', 'POST'])
@login_required
def addpost():
    if current_user.is_authenticated:
        form = PostForm()
        if form.validate_on_submit():
            project_post = Project(title=form.title.data, type=form.type.data, content=form.content.data, author=current_user)
            #interesting note: the request processes there to be data in the multiple file field and therefore it isn't as simple as checking the
            # data from request; rather, we can check if there is no filename associated with the MultipleFileField
            upload = request.files['files']
            if upload.filename != '':

                project_post.files = save_project_files(form)
            type_image = set_type_image(form.type.data)
            home_post = HomePost(type_image=type_image, content=form.synopsis.data, project=project_post)
            db.session.add(project_post)
            db.session.add(home_post)
            db.session.commit()
            flash('Post has been created.', 'success')
            return redirect(url_for('main.home'))
        return render_template('addpost.html', title="New Post",form=form)
    else:
        return redirect(url_for('main.home'))

@posts.route('/post/<int:proj_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(proj_id):
    project_post = Project.query.get_or_404(proj_id)
    home_post = HomePost.query.filter_by(project_id=proj_id).first()
    if project_post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        project_post.title = form.title.data
        project_post.type = form.type.data
        project_post.content = form.content.data
        upload = request.files['files']
        if upload.filename != '':
            delete_project_files(project_post)
            project_post.files = save_project_files(form)
        if request.form.get('del-images'):
            delete_project_files(project_post)
            project_post.files = None
        home_post.type_image = set_type_image(form.type.data)
        home_post.content = form.synopsis.data
        db.session.commit()
        flash('Your post has been updated.', 'success')
        return redirect(url_for('posts.project', title=project_post.title))
    elif request.method == 'GET':
        form.title.data = project_post.title #filling in the form with the current data
        form.synopsis.data = home_post.content
        form.type.data = project_post.type
        form.content.data = project_post.content
    return render_template('addpost.html', title="Update Post", form=form, legend='Update Post', update=True)

@posts.route('/post/<int:proj_id>/delete', methods=['POST'])
@login_required
def delete_post(proj_id):
    project_post = Project.query.get_or_404(proj_id)
    home_post = HomePost.query.filter_by(project_id=proj_id).first()
    if project_post.author != current_user:
        abort(403)
    delete_project_files(project_post)
    db.session.delete(project_post)
    db.session.delete(home_post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

personalWebsite/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from personalWebsite import db, bcrypt
from personalWebsite.users.forms import LoginForm
from personalWebsite.models import User
from personalWebsite.users.utils import is_safe_url

users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect('main.home')
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            if not is_safe_url(next_page):
                return flask.abort(400)
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Check your password, Vince', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

personalWebsite/templates/coding.html
{% extends "layout.html" %}

{% block content %}
<div class="container post-section">
  <h1 class="display-4 text-white-2 text-center">Coding</h1>
  <hr>
  <div class="row text-center">
    {% for post in posts.items %}
    <div class="col-lg-9">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <a class = "card-title" href="{{ url_for('posts.project', title=post.title) }}">{{ post.title }}</a>
        </div>
        <div class="card-body">
          <p class= "card-text max-length-card ellipsis-text text-left">{{ post.content }}</p>
        </div>
        <div class="card-footer text-right">
          <small class="text-muted">Date posted: {{ post.date_posted.strftime('%m-%d-%Y') }}</small>
        </div>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', proj_id=post.id) }}">Update Post</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>

        {% endif %}
      </div>
    </div>
    <!--Delete Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', proj_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container mt-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.coding', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.coding', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        <small>...</small>
      {% endif %}
    {% endfor %}
  </div>
</div>

{% endblock content %}

personalWebsite/templates/homepage.html
{% extends "layout.html" %}
{%block content%}
    <div class="jumbotron" id="home-jumbotron">
      <div class="container text-white" id="jumbotron-container">
        <h1 class="display-4">See Everything I've Ever Done</h1>
        <p class="lead">My name is Vincent Monteleone. I'm currently about to graduate from St. John's University, Majoring in Computer Science.
        This website embodies the energy and pride of all my coding, writing, photography, and related art works. The best part is this entire website is a project itself...
        </p>
        <div class="text-right">
          <a class="btn btn-info btn-lg mr-4" href="{{ url_for('main.about') }}"> Learn More</a>
        </div>
      </div>
    </div>
    <section class="home-articles">
      <div class="container-fluid text-center">
        <h1 class="display-4 text-white-2"><i>Latest Projects:</i></h1>
        <hr class="my-2">
        <div class="row">
          {% for post in posts.items %}
          <div class="col-md-6" >
            <div class="card mb-4 shadow-lg border-0">
              <div class="card-header">
                <img  src="{{ url_for('static', filename=post.type_image ) }}" class="project_type_image">
                <a class = "card-title" href="{{ url_for('posts.project', title=post.project.title) }}">{{ post.project.title }}</a>
              </div>
              <div class="card-body">
                <p class= "card-text"> {{ post.content }} </p>
              </div>
              <div class="card-footer text-right">
                <small class="text-muted">Date posted: {{ post.project.date_posted.strftime('%m-%d-%Y') }}</small>
              </div>
              {% if post.author == current_user %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', post_id=post.id) }}">Update Post</a>
                  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      </section>
      <div class="container mt-5 text-center">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if posts.page == page_num %}
              <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            <small>...</small>
          {% endif %}
        {% endfor %}
      </div>
{%endblock content%}

personalWebsite/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Vince Monteleone: Designer // Developer">
    <meta property="og:site_name" content="Vince Monteleone | Portfolio ">
    <meta property="og:url" content="https://www.vincemonte.com/">
    <meta property="og:description" content="A collection of my work and projects, including: coding, writing, photography, and more! Come see what I've been getting up to lately.">
    <meta property="og:type" content="profile">
    <meta property="og:image" content="{{ url_for('static', filename=’images/DummyOG.png’ ) }}">

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='bootstrap-reboot.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,700;1,400&family=Work+Sans:ital,wght@0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,400;0,500;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='devices.css')}}">
    <!--Improved Favicon-->
  	<link rel="apple-touch-icon" sizes="57x57" href="{{url_for('static', filename='images/favicons/apple-icon-57x57.png')}}">
  	<link rel="apple-touch-icon" sizes="60x60" href="{{url_for('static', filename='images/favicons/apple-icon-60x60.png')}}">
  	<link rel="apple-touch-icon" sizes="72x72" href="{{url_for('static', filename='images/favicons/apple-icon-72x72.png')}}">
  	<link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static', filename='images/favicons/apple-icon-76x76.png')}}">
  	<link rel="apple-touch-icon" sizes="114x114" href="{{url_for('static', filename='images/favicons/apple-icon-114x114.png')}}">
  	<link rel="apple-touch-icon" sizes="120x120" href="{{url_for('static', filename='images/favicons/apple-icon-120x120.png')}}">
  	<link rel="apple-touch-icon" sizes="144x144" href="{{url_for('static', filename='images/favicons/apple-icon-144x144.png')}}">
  	<link rel="apple-touch-icon" sizes="152x152" href="{{url_for('static', filename='images/favicons/apple-icon-152x152.png')}}">
  	<link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/favicons/apple-icon-180x180.png')}}">
  	<link rel="icon" type="image/png" sizes="192x192"  href="{{url_for('static', filename='images/favicons/android-icon-192x192.png')}}">
  	<link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicons/favicon-32x32.png')}}">
  	<link rel="icon" type="image/png" sizes="96x96" href="{{url_for('static', filename='images/favicons/favicon-96x96.png')}}">
  	<link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images/favicons/favicon-16x16.png')}}">
  	<link rel="manifest" href="{{url_for('static', filename='images/favicons/manifest.json')}}">
  	<meta name="msapplication-TileColor" content="#ffffff">
  	<meta name="msapplication-TileImage" content="{{url_for('static', filename='images/favicons/ms-icon-144x144.png')}}">
  	<meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,400;1,500&display=swap" rel="stylesheet">
    <title>Vincent Monteleone's Current Workflow: coding and personal-writing projects!</title>
  </head>

  <body>
    <header>

      <nav class="navbar fixed-top navbar-expand-xl navbar-dark" id="navigation-bar">
        <a href="{{url_for('main.home')}}"><img class="navbar-logo" id="navbar-logo" src="{{url_for('static', filename='images/VLM_Logo_Blue.svg')}}" alt="restaurant logo (rooster)"></a>
        <span class="navbar-brand" id="navbar-brand">Vincent Monteleone</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsing-navbar" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation" style="background:#1D2327;">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsing-navbar">
          <ul class="navbar-nav ml-auto" id="nav-list-container">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.coding')}}">Coding</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.updates')}}">Updates</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.writings')}}">Writings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.photography')}}">Photography</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.about')}}">About</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.addpost')}}">Add Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a href="https://github.com/vincemonte"><img class="image-link" id="image-link" src="{{url_for('static', filename='images/GitHub_White.svg')}}"></a>
            </li>
          </ul>
        </div>
      </nav>

    </header>
    <main role="main">
      {%with messages = get_flashed_messages(with_categories=true) %}
            {%if messages%}
              {%for category, message in messages%}
              <div class="alert alert-{{category}}">
                {{message}}
              </div>
              {% endfor %}
            {% endif %}
        {% endwith%}
        {% block content %}{% endblock %}
    </main>
    <footer>@vincemonte 2020</footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='pageUtils.js')}}"></script>
  </body>
</html>

personalWebsite/templates/login.html
{% extends "layout.html" %}

{%block content%}
  <div class="form-section text-white-2 ">
    <!--Will post the information to the same route (hence empty string)-->
    <form method="POST" action="">
      <!--adding a csf token-->
      {{form.hidden_tag() }}
      <fieldset class = "form-group">
        <legend class="mb-4 text-center"> {{title}} </legend>

        <div class="form-group row">
          <div class="col-sm-3 mx-auto">
          {{ form.username.label(class="form-control-label")}}
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-md is-invalid")}}
            <div class="invalid-feedback">
                 {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                 {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-md")}}
          {% endif %}
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-3 mx-auto">
          {{ form.password.label(class="form-control-label")}}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-md is-invalid")}}
            <div class="invalid-feedback">
                 {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                 {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-md")}}
          {% endif %}
        </div>
    </div>


    </fieldset>
      <div class="form-group text-center">

            {{form.submit(class="btn btn-outline-info")}}

      </div>
  </form>
</div>
{%endblock content %}

personalWebsite/templates/photography.html
{% extends "layout.html" %}
{% block content %}
<div class="container post-section">
  <h1 class="display-4 text-white-2 text-center">Photography</h1>
  <hr>
  <div class="row text-center">
    {% for post in posts.items %}
    <div class="col-lg-9">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <a class = "card-title" href="{{ url_for('posts.project', title=post.title) }}">{{ post.title }}</a>
        </div>
        <img class="card-image-top post-photo" src="{{url_for('static', filename=files[loop.index0])}}">
        <div class="card-footer text-right">
          <small class="text-muted">Date posted: {{ post.date_posted.strftime('%m-%d-%Y') }}</small>
        </div>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', proj_id=post.id) }}">Update Post</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', proj_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container mt-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.photography', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.photography', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        <small>...</small>
      {% endif %}
    {% endfor %}
  </div>
</div>


{% endblock content %}

personalWebsite/templates/projects.html
{% extends "layout.html" %}

personalWebsite/templates/updates.html
{% extends "layout.html" %}

{% block content %}
<div class="container post-section">
  <h1 class="display-4 text-white-2 text-center">General Updates</h1>
  <hr>
  <div class="row text-center">
    {% for post in posts.items %}
    <div class="col-lg-9">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <a class = "card-title" href="{{ url_for('posts.project', title=post.title) }}">{{ post.title }}</a>
        </div>
        <div class="card-body">
          <p class= "card-text max-length-card ellipsis-text text-left">{{ post.content }}</p>
        </div>
        <div class="card-footer text-right">
          <small class="text-muted">Date posted: {{ post.date_posted.strftime('%m-%d-%Y') }}</small>
        </div>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', proj_id=post.id) }}">Update Post</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>

        {% endif %}
      </div>
    </div>
    <!--Delete Modal-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', proj_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container mt-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.updates', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.updates', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        <small>...</small>
      {% endif %}
    {% endfor %}
  </div>
</div>

{% endblock content %}

personalWebsite/templates/writings.html
{% extends "layout.html" %}
{% block content %}
<div class="container post-section">
  <h1 class="display-4 text-white-2 text-center">Writings</h1>
  <hr>
  <div class="row text-center">
    {% for post in posts.items %}
    <div class="col-lg-9">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <a class = "card-title" href="{{ url_for('posts.project', title=post.title) }}">{{ post.title }}</a>
        </div>
        <div class="card-body">
          <p class= "card-text ellipsis-text">{{ post.content }}</p>
        </div>
        <div class="card-footer text-right">
          <small class="text-muted">Date posted: {{ post.date_posted.strftime('%m-%d-%Y') }}</small>
        </div>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', proj_id=post.id) }}">Update Post</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>

        {% endif %}
      </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', proj_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container mt-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.writings', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.writings', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        <small>...</small>
      {% endif %}
    {% endfor %}
  </div>
</div>

{% endblock content %}